const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { compileDesign, simulateDesign } = require('../backend/verilog-backend');

const html = fs.readFileSync(path.join(__dirname, '..', 'DCDV.html'), 'utf8');
const sourceFunction = name => {
  const match = html.match(new RegExp(`^        (?:async )?function ${name}\\([^]*?^        }`, 'm'));
  assert.ok(match, name);
  return match[0];
};
const generated = 'module generated(input a, output y); assign y = a; endmodule';
const manual = '// Hand-written inverter\nmodule manual(input a, output y); assign y = ~a; endmodule';

function fixture(api = async () => ({ ok: true, selectedTop: 'manual', moduleCandidates: ['manual'], ports: [
  { name: 'a', direction: 'input', width: 1 }, { name: 'y', direction: 'output', width: 1 },
] })) {
  const elements = Object.fromEntries(['verilog-editor', 'top-module-select', 'btn-run-compile',
    'btn-compile-current-hdl', 'compiled-design-summary', 'compile-console', 'wave-refresh-status']
    .map(id => [id, { value: '', innerHTML: id, textContent: '', disabled: false }]));
  elements['verilog-editor'].value = manual;
  const effects = { requests: [], toasts: [], previews: 0, syncs: 0 };
  const compiledDesign = { compileOk: false, ports: [], consoleEntries: [], outputs: [] };
  const context = vm.createContext({
    document: { getElementById: id => elements[id] },
    lucide: { createIcons() {} }, compiledDesign,
    activeDefineModeName: '逻辑表达式',
    lastAutoGeneratedHdl: { code: generated },
    getSelectedHdlModeName: () => '数据流',
    getCurrentDefineSourceSignature: () => 'logic:A',
    generateDynamicVerilog: () => generated,
    syncHdlFromCurrentDefinition() { effects.syncs++; elements['verilog-editor'].value = generated; },
    switchTab() {}, refreshBackendHealth: async () => {},
    showToast: message => effects.toasts.push(message),
    updateWorkflowBar() {}, updateWaveBlockingHint() {}, syncWaveData() {},
    renderCompileConsole() {},
    updateTopModuleSelect(candidates, selected = '') { elements['top-module-select'].value = selected; },
    getBackendConnectionMessage: () => 'backend unavailable',
    callLocalApi: async (endpoint, { body }) => { effects.requests.push({ endpoint, body }); return api(endpoint, body); },
    waveData: { steps: 4, stepNs: 10, signals: [
      { name: 'a', kind: 'in', width: 1, radix: 'bin', values: [0, 1, 1, 0] },
      { name: 'y', kind: 'out', width: 1, radix: 'bin', values: [0, 0, 0, 0] },
    ] },
    renderWaveformUI() {}, scheduleWaveBackendSimulation() {},
    evaluateSimulation: () => effects.previews++,
  });
  vm.runInContext(`let acceptedCurrentHdlCode = null, hdlCompileInFlight = false;
    let waveBackendSimulationInFlight = false, waveBackendSimulationQueued = false;\n` + [
    'getVerilogEditorCode', 'setCompiledSummary', 'setCompileConsoleEntries', 'appendCompileConsoleEntry',
    'invalidateCompiledDesign', 'syncCompiledDesignFromResponse', 'runCompile',
    'rememberAutoGeneratedHdl', 'canAutoOverwriteHdlEditor', 'isCurrentHdlAccepted', 'handleVerilogEditorInput',
    'ensureDefinitionAndHdlConsistency', 'canUseDefinitionWavePreview', 'useCompiledVerilogWaveModel',
    'runSimulation', 'setWaveRefreshStatus', 'serializeWaveSignalsForBackend', 'signalBitWidth', 'mergeSimulationOutputs', 'getDefaultWaveValue',
  ].map(sourceFunction).join('\n'), context);
  return { context, elements, effects, compiledDesign, editor: elements['verilog-editor'] };
}

test('ordinary compile keeps manual HDL intact and points to the explicit compile action', async () => {
  const f = fixture();
  await f.context.runCompile();
  assert.equal(f.effects.requests.length, 0);
  assert.equal(f.editor.value, manual);
  assert.match(f.elements['compiled-design-summary'].textContent, /使用当前 HDL 编译/);
});

test('explicit compile submits the editor source, retains it for simulation and prevents auto-overwrite', async () => {
  const f = fixture();
  await f.context.runCompile({ useCurrentHdl: true });
  assert.equal(f.effects.requests[0].body.code, manual);
  assert.equal(f.editor.value, manual);
  assert.equal(f.context.isCurrentHdlAccepted(), true);
  assert.equal(f.context.ensureDefinitionAndHdlConsistency('运行仿真'), true);
  assert.equal(f.context.canUseDefinitionWavePreview(), false);
  assert.equal(f.context.canAutoOverwriteHdlEditor(f.editor), false);
  assert.match(f.elements['compiled-design-summary'].textContent, /编译与仿真使用当前 HDL/);
  await f.context.runSimulation();
  assert.equal(f.effects.requests[1].endpoint, '/api/verilog/simulate');
  assert.equal(f.effects.requests[1].body.code, manual);
  assert.equal(f.effects.previews, 0);
});

test('explicit compile preserves even a previously generated source when definitions change', async () => {
  const f = fixture();
  f.editor.value = generated;
  f.context.generateDynamicVerilog = () => '// new definition';
  await f.context.runCompile({ useCurrentHdl: true });
  assert.equal(f.effects.requests[0].body.code, generated);
  assert.equal(f.effects.syncs, 0);
  assert.equal(f.context.canAutoOverwriteHdlEditor(f.editor), false);
  assert.equal(f.context.canUseDefinitionWavePreview(), false);
});

test('editing or regenerating HDL clears the prior manual-source choice', async () => {
  const f = fixture();
  await f.context.runCompile({ useCurrentHdl: true });
  f.editor.value += '\n// edit';
  f.context.handleVerilogEditorInput();
  assert.equal(f.context.isCurrentHdlAccepted(), false);
  assert.equal(f.compiledDesign.compileOk, false);
  assert.equal(f.context.ensureDefinitionAndHdlConsistency('编译检查'), false);
  await f.context.runCompile({ useCurrentHdl: true });
  f.context.rememberAutoGeneratedHdl('数据流', generated);
  f.editor.value = generated;
  assert.equal(f.context.isCurrentHdlAccepted(), false);
  assert.equal(f.context.canAutoOverwriteHdlEditor(f.editor), true);
});

test('empty explicit source is not regenerated, while normal automatic synchronization still works', async () => {
  const f = fixture();
  f.editor.value = '  \n';
  await f.context.runCompile({ useCurrentHdl: true });
  assert.equal(f.effects.requests.length, 0);
  assert.equal(f.effects.syncs, 0);
  assert.equal(f.context.isCurrentHdlAccepted(), false);
  await f.context.runCompile();
  assert.equal(f.effects.syncs, 1);
  assert.equal(f.effects.requests[0].body.code, generated);
  f.context.generateDynamicVerilog = () => '// changed definition';
  await f.context.runCompile();
  assert.equal(f.effects.syncs, 2);
});

test('both compile buttons lock during a request and stale results never mark edited code compiled', async () => {
  let finish;
  const f = fixture(() => new Promise(resolve => { finish = resolve; }));
  const pending = f.context.runCompile({ useCurrentHdl: true });
  assert.equal(f.elements['btn-run-compile'].disabled, true);
  assert.equal(f.elements['btn-compile-current-hdl'].disabled, true);
  await f.context.runCompile({ useCurrentHdl: true });
  assert.equal(f.effects.requests.length, 1);
  f.editor.value += '\n// changed during compile';
  f.context.handleVerilogEditorInput();
  finish({ ok: true, selectedTop: 'manual', ports: [{ name: 'a', direction: 'input', width: 1 }] });
  await pending;
  assert.equal(f.compiledDesign.compileOk, false);
  assert.match(f.elements['compiled-design-summary'].textContent, /编译期间已修改/);
  for (const id of ['btn-run-compile', 'btn-compile-current-hdl']) {
    assert.equal(f.elements[id].disabled, false);
    assert.equal(f.elements[id].innerHTML, id);
  }
});

test('failed compile or backend error cannot fall back to definition simulation', async () => {
  for (const api of [async () => ({ ok: false, compilerLog: 'syntax error' }), async () => { throw new Error('offline'); }]) {
    const f = fixture(api);
    await f.context.runCompile({ useCurrentHdl: true });
    await f.context.runSimulation();
    assert.equal(f.effects.previews, 0);
    assert.equal(f.compiledDesign.compileOk, false);
    assert.equal(f.elements['btn-compile-current-hdl'].disabled, false);
  }
});

test('manual HDL compiles and simulates through real Icarus using its own logic', async () => {
  const f = fixture((endpoint, body) => endpoint.endsWith('/compile') ? compileDesign(body) : simulateDesign(body));
  await f.context.runCompile({ useCurrentHdl: true });
  assert.equal(f.compiledDesign.compileOk, true, f.compiledDesign.compilerLog);
  await f.context.runSimulation();
  assert.deepEqual(Array.from(f.context.waveData.signals.find(signal => signal.name === 'y').values), [1, 0, 0, 1]);
  assert.equal(f.effects.previews, 0);
});
